name: sarthi
description: A new Flutter project.


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  dots_indicator: ^2.0.0
  google_fonts: ^2.0.0
  firebase_auth: ^1.0.1
  cloud_firestore: ^1.0.1
  firebase_core: ^1.0.1
  provider: ^5.0.0
  geolocator: ^7.2.0+1
  google_maps_flutter: ^2.0.6
  geocoder: ^0.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true


  assets:
  - images/

